export const FETCH_SCHEDULE_START = 'FETCH_SCHEDULE_START';
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';
export const FETCH_SCHEDULE_ERROR = 'FETCH_SCHEDULE_ERROR';

export const FETCH_GAMETHREAD_START = 'FETCH_GAMETHREAD_START';
export const FETCH_GAMETHREAD_SUCCESS = 'FETCH_GAMETHREAD_SUCCESS';
export const FETCH_GAMETHREAD_ERROR = 'FETCH_GAMETHREAD_ERROR';
